# 조인스랜드 부동산
https://price.joinsland.joins.com/ 데이터 크롤링


https://price.joinsland.joins.com/area/?mcateGroup=A1&mcateCode=A1A3A4&areaCode=1168010600

In [1]:
import pandas as pd

url = 'http://price.joinsland.joins.com/area/index.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=1168010600'
dfs = pd.read_html(url, 'lxml')
dfs

ValueError: No tables found

## 페이지 소스 확인
메뉴에서 "보기 > 개발자 보기 > 소스보기" 선택하여 페이지 소스를 확인

크롬 개발자 도구로 table과 데이터가 보이지만, 소스 보기를 하면 소스에는 데이터가 보이지 않는다

id="sesae_info_gu" 인 div 태그에 table 도 없고 데이터도 없다

이 처럼 크롬개발자 도구에서는 데이터가 있으나, 페이지 소스에는 데이터가 없는 경우는 다음 두 가지 중의 하나

- Ajax로 데이터를 요청하여 데이터를 표현 → 데이터 요청 URL을 따로 분석
- JavaScript가 실행되어 데이터를 표현 → Selenium 사용

Ajax (Asynchronous JavaScript and XML, 에이잭스)는 자바스크립트로 요청하는 비동기 데이터 요청.

## Ajax 데이터 요청 확인

- Network 탭을 열고
- 검색조건이 달라질 때('동'을 선택), 어떤 데이터가 오가는지 살펴본다
- 요청/응답 데이터들 중에 데이터기 포함되어 오가는지 살펴본다

## joins.com/ajax
여기서는 다음 URL로 데이터가 요청/응답 되었음을 확인할 수 있다

https://price.joinsland.joins.com/ajax/price.info.dongapt.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=1168010600&danjiId=&ptype=&cpId=&aptamt=&aptarea=&aptcnt=&aptIpjudate=

아래 URL의 인자로 다음 값들이 전달
http://price.joinsland.joins.com/ajax/price.info.dongapt.asp
- mcateGroup: A1=아파트, A6=오피스텔
- mcateCode: A1A3A4
- areaCode=1168010600
결과적으로 지역코드(areaCode)만 지정하면 가격 데이터를 가져올 수 있다.

## 지역이름과 코드
(참고) joinsland.joins.com 자체에도 법정동을 조회하는 내용이 있으나 데이터가 온전한 JSON 이 아니어서 가공하기 어렵다

In [4]:
# 구/시/군 (MCODE) 코드 가져오기
import requests

# 서울특별시 하위 '구/시/군' 읽기
area_code = '110000000'
url = "https://price.joinsland.joins.com/ajax/price.info.dongapt.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=" + area_code
r = requests.get(url).text
print(r)

			<div class="dong_apt">
				<h3></h3>
				<div class="tbl_box">
				<table class="tbl_compare">
					<caption class="screen_hide">게시판 목록</caption>
					<colgroup>
						<col width="194">
						<col width="82">
						<col width="190">
						<col width="46">
						<col width="190">
						<col width="46">
						<!--col width="60"-->
						<col width="226">
					</colgroup>
					<thead>
						<tr>
							<th scope="col" class="tit_danzi">단지명</th>
							<th scope="col" class="tit_area">면적 <em>(㎡)</em></th>
							<th scope="col" class="tit_price"><strong>매매가</strong> <em>(만원)</em></th>
							<th scope="col" class="tit_maemul">매물</th>
							<th scope="col" class="tit_price"><strong>전세가</strong> <em>(만원)</em></th>
							<th scope="col" class="tit_maemul">매물</th>
							<!--th scope="col" class="tit_comparison"><a href="#" title="비교">비교</a></th-->
							<th scope="col" class="tit_inquiry"><a href="#">문의처</a></th>
						</tr>
					</thead>
					<tbody>


					</tbody>
				</table>
				</div>
			</div><!-- // dong_apt -->

## 법정동 이름과 코드
부동산 정보등에는 법정동 코드가 사용된다.

법정동 코드(8자리)
2(시/도) + 2자리(구/군/구) + 2자리(읍/면/동) + 2자리(리/단지)

In [5]:
import pandas as pd

def get_areacode():
    df_areacode = pd.read_csv('https://goo.gl/tM6r3v', sep='\t', dtype={'법정동코드':str, '법정동명':str})
    df_areacode = df_areacode[df_areacode['폐지여부'] == '존재']
    df_areacode = df_areacode[['법정동코드', '법정동명']]
    return df_areacode

def get_province():
    df_areacode = get_areacode()
    df_province = df_areacode[ df_areacode['법정동코드'].str.contains('\d{2}0{8}|36110{6}')]
    return df_province

In [6]:
df_areacode = get_areacode()
df_province = get_province()

In [7]:
df_province

            법정동코드     법정동명
0      1100000000    서울특별시
2615   2600000000    부산광역시
2912   2700000000    대구광역시
3244   2800000000    인천광역시
3579   2900000000    광주광역시
3825   3000000000    대전광역시
4009   3100000000    울산광역시
4241   3611000000  세종특별자치시
4391   4100000000      경기도
10867  4200000000      강원도
13666  4300000000     충청북도
16797  4400000000     충청남도
22050  4500000000     전라북도
25397  4600000000     전라남도
30169  4700000000     경상북도
39299  4800000000     경상남도
45741  5000000000  제주특별자치도

In [8]:
df_areacode.head(10)

        법정동코드           법정동명
0  1100000000          서울특별시
1  1111000000      서울특별시 종로구
2  1111010100  서울특별시 종로구 청운동
3  1111010200  서울특별시 종로구 신교동
4  1111010300  서울특별시 종로구 궁정동
5  1111010400  서울특별시 종로구 효자동
6  1111010500  서울특별시 종로구 창성동
7  1111010600  서울특별시 종로구 통의동
8  1111010700  서울특별시 종로구 적선동
9  1111010800  서울특별시 종로구 통인동

In [9]:
df_areacode[ df_areacode['법정동명'].str.contains('서울특별시 강남구') ]

           법정동코드            법정동명
1003  1168000000       서울특별시 강남구
1037  1168010100   서울특별시 강남구 역삼동
1039  1168010300   서울특별시 강남구 개포동
1040  1168010400   서울특별시 강남구 청담동
1041  1168010500   서울특별시 강남구 삼성동
1042  1168010600   서울특별시 강남구 대치동
1043  1168010700   서울특별시 강남구 신사동
1044  1168010800   서울특별시 강남구 논현동
1045  1168011000  서울특별시 강남구 압구정동
1046  1168011100   서울특별시 강남구 세곡동
1047  1168011200   서울특별시 강남구 자곡동
1048  1168011300   서울특별시 강남구 율현동
1049  1168011400   서울특별시 강남구 일원동
1050  1168011500   서울특별시 강남구 수서동
1053  1168011800   서울특별시 강남구 도곡동

## 데이터 전처리

In [15]:
area_code = '1168010600'
url = "https://price.joinsland.joins.com/ajax/price.info.dongapt.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=" + area_code
dfs = pd.read_html(url, encoding='utf-8')
dfs

[                    단지명 면적 (㎡)           매매가 (만원)  매물           전세가 (만원)  \
 0           개포우성1차(아파트)    102  222,500 ~ 243,500   0    77,500 ~ 87,500
 1           개포우성1차(아파트)    148  277,500 ~ 302,500   0  100,000 ~ 115,000
 2           개포우성1차(아파트)    181  320,000 ~ 360,000   0  115,000 ~ 135,000
 3           개포우성1차(아파트)    214  350,000 ~ 390,000   0  132,500 ~ 150,000
 4           개포우성2차(아파트)    101  222,500 ~ 243,500   0    77,500 ~ 87,500
 5           개포우성2차(아파트)    146  277,500 ~ 302,500   0  100,000 ~ 120,000
 6           개포우성2차(아파트)    180  330,000 ~ 375,000   0  115,000 ~ 135,000
 7    대치대우아이빌멤버스4차(주상복합)     31    19,500 ~ 21,000   0    16,000 ~ 18,000
 8    대치대우아이빌멤버스4차(주상복합)     39    22,000 ~ 24,000   0    20,000 ~ 22,000
 9    대치대우아이빌멤버스4차(주상복합)     44    29,500 ~ 31,500   1    25,000 ~ 27,000
 10   대치대우아이빌멤버스4차(주상복합)    51B    33,000 ~ 36,000   0    26,000 ~ 28,000
 11   대치대우아이빌멤버스4차(주상복합)     53    34,000 ~ 37,000   0    29,000 ~ 32,000
 12   대치대우아이빌멤버스4차(주상복합)     58    38,000 ~ 41,000   0    32,000 ~ 34,000
 13   대치대우아이빌멤버스4차(주상복합)     63    45,000 ~ 48,000   0    34,000 ~ 36,000
 14   대치대우아이빌멤버스4차(주상복합)     68    45,000 ~ 48,000   1    34,000 ~ 36,000
 15     대치대우아이빌명문가(주상복합)    41A    30,000 ~ 32,000   1    23,500 ~ 25,000
 16     대치대우아이빌명문가(주상복합)    43B    30,000 ~ 32,000   1    23,500 ~ 25,000
 17     대치대우아이빌명문가(주상복합)     45    30,500 ~ 32,500   0    24,500 ~ 26,000
 18     대치대우아이빌명문가(주상복합)     53    34,000 ~ 36,000   0    26,500 ~ 29,500
 19     대치대우아이빌명문가(주상복합)     58    40,000 ~ 43,000   0    31,500 ~ 34,000
 20     대치대우아이빌명문가(주상복합)     66    45,000 ~ 47,000   0    33,500 ~ 36,500
 21        대치롯데캐슬리베(아파트)    146  215,000 ~ 232,500   0  130,000 ~ 140,000
 22          대치삼성1차(아파트)     85  150,000 ~ 161,500   1    65,000 ~ 71,000
 23          대치삼성1차(아파트)    108  181,500 ~ 192,500   0   87,500 ~ 100,000
 24          대치삼성1차(아파트)    124  204,000 ~ 224,000   0  111,500 ~ 124,000
 25          대치삼성1차(아파트)    133  216,500 ~ 239,000   0  117,500 ~ 130,000
 26          대치삼성1차(아파트)    139  215,000 ~ 239,000   0  117,500 ~ 130,000
 27          대치쌍용1차(재건축)    102  176,000 ~ 191,000   0    52,500 ~ 60,000
 28          대치쌍용1차(재건축)    150  211,000 ~ 236,000   0    72,500 ~ 80,000
 29          대치쌍용1차(재건축)    173  250,000 ~ 270,000   0    80,000 ~ 87,500
 ..                  ...    ...                ...  ..                ...
 125             은마(재건축)    101  178,000 ~ 187,000   0    41,500 ~ 48,750
 126             은마(재건축)    115  200,500 ~ 210,500   0    51,500 ~ 59,000
 127     테헤란로대우아이빌(주상복합)    38A    28,500 ~ 31,500   0    22,000 ~ 24,500
 128     테헤란로대우아이빌(주상복합)    39B    28,500 ~ 31,500   0    22,000 ~ 24,500
 129     테헤란로대우아이빌(주상복합)    40C    28,500 ~ 31,500   0    22,000 ~ 24,500
 130     테헤란로대우아이빌(주상복합)    42A    32,500 ~ 35,500   0    24,000 ~ 26,500
 131     테헤란로대우아이빌(주상복합)    44B    32,500 ~ 35,500   0    24,000 ~ 26,500
 132     테헤란로대우아이빌(주상복합)    46A    33,000 ~ 36,000   0    25,000 ~ 27,500
 133     테헤란로대우아이빌(주상복합)    47B    33,000 ~ 36,000   1    25,000 ~ 27,500
 134     테헤란로대우아이빌(주상복합)    47C    33,000 ~ 36,000   0    25,000 ~ 27,500
 135     테헤란로대우아이빌(주상복합)     79    61,500 ~ 65,000   0    44,000 ~ 48,500
 136     테헤란로대우아이빌(주상복합)    87A    51,000 ~ 54,500   0    41,000 ~ 43,000
 137     테헤란로대우아이빌(주상복합)    89B    51,000 ~ 54,500   0    41,000 ~ 43,000
 138          포스코더샵(아파트)    168  202,500 ~ 220,000   0  127,500 ~ 137,500
 139          포스코더샵(아파트)    208  237,500 ~ 252,500   0  137,500 ~ 147,500
 140           하이캐슬(아파트)   104A  130,500 ~ 142,000   0    72,000 ~ 79,000
 141           하이캐슬(아파트)   104B  130,500 ~ 142,000   0    72,000 ~ 79,000
 142           하이캐슬(아파트)   104C  130,500 ~ 142,000   0    72,000 ~ 79,000
 143           하이캐슬(아파트)   105D  130,500 ~ 142,000   0    72,000 ~ 79,000
 144     한보미도맨션1,2차(아파트)   113A  207,500 ~ 225,000   0    70,000 ~ 75,500
 145     한보미도맨션1,2차(아파트)   114B  210,000 ~ 220,000   0    69,000 ~ 76,000
 146     한보미도맨션1,2차(아파트)    135  242,500 ~ 257,500   0    85,000 ~ 93,500
 147     한보미도맨션1,2차(아파트)    148  255,000 ~ 270,000   0   90,000 ~ 102,500
 148     한보미도맨션1,2차(아파트)    152  257,500 ~ 272,500   0   92,500 ~ 102,500
 149     한보미도맨션1,2차(아파트)    183  305,000 ~ 322,500   0  110,000 ~ 120,000
 150     한보미도맨션1,2차(아파트)    188  297,500 ~ 310,000   0  110,000 ~ 120,000
 151     한보미도맨션1,2차(아파트)    217  345,000 ~ 362,500   0  125,000 ~ 135,000
 152     한보미도맨션1,2차(아파트)    220  352,500 ~ 365,000   0  130,000 ~ 140,000
 153             현대(아파트)   101A  152,500 ~ 163,500   0    48,000 ~ 55,000
 154             현대(아파트)   101B  152,500 ~ 163,500   0    48,000 ~ 55,000

      매물.1  문의처
 0       0  NaN
 1       0  NaN
 2       0  NaN
 3       0  NaN
 4       0  NaN
 5       0  NaN
 6       0  NaN
 7       0  NaN
 8       0  NaN
 9       1  NaN
 10      0  NaN
 11      1  NaN
 12      0  NaN
 13      0  NaN
 14      0  NaN
 15      0  NaN
 16      2  NaN
 17      0  NaN
 18      0  NaN
 19      0  NaN
 20      0  NaN
 21      0  NaN
 22      0  NaN
 23      0  NaN
 24      0  NaN
 25      0  NaN
 26      0  NaN
 27      0  NaN
 28      0  NaN
 29      0  NaN
 ..    ...  ...
 125     0  NaN
 126     0  NaN
 127     0  NaN
 128     0  NaN
 129     0  NaN
 130     0  NaN
 131     1  NaN
 132     0  NaN
 133     0  NaN
 134     0  NaN
 135     1  NaN
 136     0  NaN
 137     0  NaN
 138     0  NaN
 139     0  NaN
 140     0  NaN
 141     0  NaN
 142     0  NaN
 143     0  NaN
 144     0  NaN
 145     0  NaN
 146     0  NaN
 147     0  NaN
 148     0  NaN
 149     0  NaN
 150     0  NaN
 151     0  NaN
 152     0  NaN
 153     0  NaN
 154     0  NaN

 [155 rows x 7 columns]]

In [17]:
dfs[0].head(10)

,단지명,면적 (㎡),매매가 (만원),매물,전세가 (만원),매물.1,문의처
0,개포우성1차(아파트),102,"222,500 ~ 243,500",0,"77,500 ~ 87,500",0,NaN
1,개포우성1차(아파트),148,"277,500 ~ 302,500",0,"100,000 ~ 115,000",0,NaN
2,개포우성1차(아파트),181,"320,000 ~ 360,000",0,"115,000 ~ 135,000",0,NaN
3,개포우성1차(아파트),214,"350,000 ~ 390,000",0,"132,500 ~ 150,000",0,NaN
4,개포우성2차(아파트),101,"222,500 ~ 243,500",0,"77,500 ~ 87,500",0,NaN
5,개포우성2차(아파트),146,"277,500 ~ 302,500",0,"100,000 ~ 120,000",0,NaN
6,개포우성2차(아파트),180,"330,000 ~ 375,000",0,"115,000 ~ 135,000",0,NaN
7,대치대우아이빌멤버스4차(주상복합),31,"19,500 ~ 21,000",0,"16,000 ~ 18,000",0,NaN
8,대치대우아이빌멤버스4차(주상복합),39,"22,000 ~ 24,000",0,"20,000 ~ 22,000",0,NaN
9,대치대우아이빌멤버스4차(주상복합),44,"29,500 ~ 31,500",1,"25,000 ~ 27,000",1,NaN

In [18]:
from bs4 import BeautifulSoup

url = 'http://price.joinsland.joins.com/ajax/price.info.dongapt.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=' + '1168010600'

r = requests.get(url).text
soup = BeautifulSoup(r, 'lxml')

In [45]:
table = soup.find('table', attrs={'class':'tbl_compare'})
trs = table.tbody.find_all('tr')

In [46]:
from pprint import pprint

pprint(trs)

[<tr>
<td class="txt_danzi" rowspan="4" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=244">개포우성1차</a><br/>(아파트)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=244&amp;ptype=1" style="color:#6284d4">102</a></td>
<td class="num_price">222,500 ~ 243,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','244')">0</a></td>
<td class="num_price">77,500 ~ 87,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','244')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="4" valign="top">
</td>
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=244&amp;ptype=2" style="color:#6284d4">148</a></td>
<td class="num_price">277,500 ~ 302,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','244')">0</a></td>
<td class="num_price">100,000 ~ 115,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','244')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=244&amp;ptype=3" style="color:#6284d4">181</a></td>
<td class="num_price">320,000 ~ 360,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','244')">0</a></td>
<td class="num_price">115,000 ~ 135,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','244')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=244&amp;ptype=4" style="color:#6284d4">214</a></td>
<td class="num_price">350,000 ~ 390,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','244')">0</a></td>
<td class="num_price">132,500 ~ 150,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','244')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="txt_danzi" rowspan="3" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=264">개포우성2차</a><br/>(아파트)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=264&amp;ptype=1" style="color:#6284d4">101</a></td>
<td class="num_price">222,500 ~ 243,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','264')">0</a></td>
<td class="num_price">77,500 ~ 87,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','264')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="3" valign="top">
</td>
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=264&amp;ptype=2" style="color:#6284d4">146</a></td>
<td class="num_price">277,500 ~ 302,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','264')">0</a></td>
<td class="num_price">100,000 ~ 120,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','264')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=264&amp;ptype=3" style="color:#6284d4">180</a></td>
<td class="num_price">330,000 ~ 375,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','264')">0</a></td>
<td class="num_price">115,000 ~ 135,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','264')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="txt_danzi" rowspan="8" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828">대치대우아이빌멤버스4차</a><br/>(주상복합)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=1" style="color:#6284d4">31</a></td>
<td class="num_price">19,500 ~ 21,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">16,000 ~ 18,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="8" valign="top">
</td>
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=2" style="color:#6284d4">39</a></td>
<td class="num_price">22,000 ~ 24,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">20,000 ~ 22,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=3" style="color:#6284d4">44</a></td>
<td class="num_price">29,500 ~ 31,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">1</a></td>
<td class="num_price">25,000 ~ 27,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">1</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=4" style="color:#6284d4">51B</a></td>
<td class="num_price">33,000 ~ 36,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">26,000 ~ 28,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=5" style="color:#6284d4">53</a></td>
<td class="num_price">34,000 ~ 37,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">29,000 ~ 32,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">1</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=6" style="color:#6284d4">58</a></td>
<td class="num_price">38,000 ~ 41,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">32,000 ~ 34,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=7" style="color:#6284d4">63</a></td>
<td class="num_price">45,000 ~ 48,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">0</a></td>
<td class="num_price">34,000 ~ 36,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13828&amp;ptype=8" style="color:#6284d4">68</a></td>
<td class="num_price">45,000 ~ 48,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13828')">1</a></td>
<td class="num_price">34,000 ~ 36,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13828')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="txt_danzi" rowspan="6" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936">대치대우아이빌명문가</a><br/>(주상복합)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=1" style="color:#6284d4">41A</a></td>
<td class="num_price">30,000 ~ 32,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">1</a></td>
<td class="num_price">23,500 ~ 25,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="6" valign="top">
</td>
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=6" style="color:#6284d4">43B</a></td>
<td class="num_price">30,000 ~ 32,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">1</a></td>
<td class="num_price">23,500 ~ 25,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">2</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=2" style="color:#6284d4">45</a></td>
<td class="num_price">30,500 ~ 32,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">0</a></td>
<td class="num_price">24,500 ~ 26,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=3" style="color:#6284d4">53</a></td>
<td class="num_price">34,000 ~ 36,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">0</a></td>
<td class="num_price">26,500 ~ 29,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=4" style="color:#6284d4">58</a></td>
<td class="num_price">40,000 ~ 43,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">0</a></td>
<td class="num_price">31,500 ~ 34,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=13936&amp;ptype=5" style="color:#6284d4">66</a></td>
<td class="num_price">45,000 ~ 47,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','13936')">0</a></td>
<td class="num_price">33,500 ~ 36,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','13936')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="txt_danzi" rowspan="1" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16349">대치롯데캐슬리베</a><br/>(아파트)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16349&amp;ptype=1" style="color:#6284d4">146</a></td>
<td class="num_price">215,000 ~ 232,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16349')">0</a></td>
<td class="num_price">130,000 ~ 140,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16349')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="1" valign="top">
</td>
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="txt_danzi" rowspan="5" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248">대치삼성1차</a><br/>(아파트)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248&amp;ptype=1" style="color:#6284d4">85</a></td>
<td class="num_price">150,000 ~ 161,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','248')">1</a></td>
<td class="num_price">65,000 ~ 71,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','248')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="5" valign="top">
</td>
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248&amp;ptype=2" style="color:#6284d4">108</a></td>
<td class="num_price">181,500 ~ 192,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','248')">0</a></td>
<td class="num_price">87,500 ~ 100,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','248')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248&amp;ptype=3" style="color:#6284d4">124</a></td>
<td class="num_price">204,000 ~ 224,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','248')">0</a></td>
<td class="num_price">111,500 ~ 124,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','248')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248&amp;ptype=4" style="color:#6284d4">133</a></td>
<td class="num_price">216,500 ~ 239,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','248')">0</a></td>
<td class="num_price">117,500 ~ 130,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','248')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=248&amp;ptype=5" style="color:#6284d4">139</a></td>
<td class="num_price">215,000 ~ 239,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','248')">0</a></td>
<td class="num_price">117,500 ~ 130,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','248')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="txt_danzi" rowspan="3" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=252">대치쌍용1차</a><br/>(재건축)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=252&amp;ptype=1" style="color:#6284d4">102</a></td>
<td class="num_price">176,000 ~ 191,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','252')">0</a></td>
<td class="num_price">52,500 ~ 60,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','252')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="3" valign="top">
</td>
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=252&amp;ptype=2" style="color:#6284d4">150</a></td>
<td class="num_price">211,000 ~ 236,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','252')">0</a></td>
<td class="num_price">72,500 ~ 80,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','252')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=252&amp;ptype=3" style="color:#6284d4">173</a></td>
<td class="num_price">250,000 ~ 270,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','252')">0</a></td>
<td class="num_price">80,000 ~ 87,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','252')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="txt_danzi" rowspan="2" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=266">대치쌍용2차</a><br/>(재건축)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=266&amp;ptype=1" style="color:#6284d4">102</a></td>
<td class="num_price">181,000 ~ 196,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','266')">0</a></td>
<td class="num_price">45,000 ~ 55,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','266')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="2" valign="top">
</td>
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=266&amp;ptype=2" style="color:#6284d4">141</a></td>
<td class="num_price">211,000 ~ 227,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','266')">0</a></td>
<td class="num_price">60,000 ~ 70,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','266')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="txt_danzi" rowspan="6" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699">대치아이파크</a><br/>(아파트)</td>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=1" style="color:#6284d4">78</a></td>
<td class="num_price">167,500 ~ 185,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">84,500 ~ 90,000</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
<td class="txt_inquiry" rowspan="6" valign="top">
</td>
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=2" style="color:#6284d4">108A</a></td>
<td class="num_price">195,000 ~ 217,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">112,500 ~ 123,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=5" style="color:#6284d4">111</a></td>
<td class="num_price">197,500 ~ 222,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">115,000 ~ 123,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=6" style="color:#6284d4">147</a></td>
<td class="num_price">245,000 ~ 267,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">150,000 ~ 167,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=7" style="color:#6284d4">154</a></td>
<td class="num_price">255,000 ~ 277,500 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">157,500 ~ 172,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr>
<td class="num_area"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=16699&amp;ptype=8" style="color:#6284d4">179</a></td>
<td class="num_price">275,000 ~ 300,000 </td>
<td class="num_maemul"><a href="javascript:goMaemul('1','16699')">0</a></td>
<td class="num_price">180,000 ~ 192,500</td>
<td class="num_maemul"><a href="javascript:goMaemul('2','16699')">0</a></td>
<!--td class="check"><input name="" type="checkbox" value="" /></td-->
</tr>,
 <tr bgcolor="#fdfdfd">
<td class="txt_danzi" rowspan="2" valign="top"><a href="/area/?mcateGroup=A1&amp;areaCode=1168010600&amp;danjiId=246">대치우성1차</a><br/>(재건축)</td>

In [49]:
rowspan_val = ''
values_list = []

for tr in trs[:20]: # 처음 20개 확인
    tds = tr.find_all('td')
    if tds[0].has_attr('rowspan'):
        rowspan_val = tds[0].text
        단지명, 면적, 매매가, 매물, 전세가, 전세_매물 = tds[0].text, tds[1].text, tds[2].text, tds[3].text, tds[4].text, tds[5].text
    else:
        단지명, 면적, 매매가, 매물, 전세가, 전세_매물 = rowspan_val, tds[0].text, tds[1].text, tds[2].text, tds[3].text, tds[4].text
    매매가_저 = int(매매가.split(' ~ ')[0].replace(',',''))
    매매가_고 = int(매매가.split(' ~ ')[1].replace(',',''))
    전세가_고 = int(전세가.split(' ~ ')[0].replace(',',''))
    전세가_저 = int(전세가.split(' ~ ')[1].replace(',',''))
    print(단지명, 면적, 매매가_저, 매매가_고, 매물, 전세가_저, 전세가_고, 전세_매물)
    values_list.append((단지명, 면적, 매매가_저, 매매가_고, 매물, 전세가_저, 전세가_고, 전세_매물))

개포우성1차(아파트) 102 222500 243500 0 87500 77500 0
개포우성1차(아파트) 148 277500 302500 0 115000 100000 0
개포우성1차(아파트) 181 320000 360000 0 135000 115000 0
개포우성1차(아파트) 214 350000 390000 0 150000 132500 0
개포우성2차(아파트) 101 222500 243500 0 87500 77500 0
개포우성2차(아파트) 146 277500 302500 0 120000 100000 0
개포우성2차(아파트) 180 330000 375000 0 135000 115000 0
대치대우아이빌멤버스4차(주상복합) 31 19500 21000 0 18000 16000 0
대치대우아이빌멤버스4차(주상복합) 39 22000 24000 0 22000 20000 0
대치대우아이빌멤버스4차(주상복합) 44 29500 31500 1 27000 25000 1
대치대우아이빌멤버스4차(주상복합) 51B 33000 36000 0 28000 26000 0
대치대우아이빌멤버스4차(주상복합) 53 34000 37000 0 32000 29000 1
대치대우아이빌멤버스4차(주상복합) 58 38000 41000 0 34000 32000 0
대치대우아이빌멤버스4차(주상복합) 63 45000 48000 0 36000 34000 0
대치대우아이빌멤버스4차(주상복합) 68 45000 48000 1 36000 34000 0
대치대우아이빌명문가(주상복합) 41A 30000 32000 1 25000 23500 0
대치대우아이빌명문가(주상복합) 43B 30000 32000 1 25000 23500 2
대치대우아이빌명문가(주상복합) 45 30500 32500 0 26000 24500 0
대치대우아이빌명문가(주상복합) 53 34000 36000 0 29500 26500 0
대치대우아이빌명문가(주상복합) 58 40000 43000 0 34000 31500 0

## DataFrame으로 만들기

In [50]:
cols = ['단지명', '면적', '매매가_저', '매매가_고', '매물', '전세가_저', '전세가_고', '전세가_매물']
df = pd.DataFrame(values_list, columns=cols)

print ("건수:", len(df))
df.head(20)

건수: 20

                   단지명   면적   매매가_저   매매가_고 매물   전세가_저   전세가_고 전세가_매물
0          개포우성1차(아파트)  102  222500  243500  0   87500   77500      0
1          개포우성1차(아파트)  148  277500  302500  0  115000  100000      0
2          개포우성1차(아파트)  181  320000  360000  0  135000  115000      0
3          개포우성1차(아파트)  214  350000  390000  0  150000  132500      0
4          개포우성2차(아파트)  101  222500  243500  0   87500   77500      0
5          개포우성2차(아파트)  146  277500  302500  0  120000  100000      0
6          개포우성2차(아파트)  180  330000  375000  0  135000  115000      0
7   대치대우아이빌멤버스4차(주상복합)   31   19500   21000  0   18000   16000      0
8   대치대우아이빌멤버스4차(주상복합)   39   22000   24000  0   22000   20000      0
9   대치대우아이빌멤버스4차(주상복합)   44   29500   31500  1   27000   25000      1
10  대치대우아이빌멤버스4차(주상복합)  51B   33000   36000  0   28000   26000      0
11  대치대우아이빌멤버스4차(주상복합)   53   34000   37000  0   32000   29000      1
12  대치대우아이빌멤버스4차(주상복합)   58   38000   41000  0   34000   32000      0
13  대치대우아이빌멤버스4차(주상복합)   63   45000   48000  0   36000   34000      0
14  대치대우아이빌멤버스4차(주상복합)   68   45000   48000  1   36000   34000      0
15    대치대우아이빌명문가(주상복합)  41A   30000   32000  1   25000   23500      0
16    대치대우아이빌명문가(주상복합)  43B   30000   32000  1   25000   23500      2
17    대치대우아이빌명문가(주상복합)   45   30500   32500  0   26000   24500      0
18    대치대우아이빌명문가(주상복합)   53   34000   36000  0   29500   26500      0
19    대치대우아이빌명문가(주상복합)   58   40000   43000  0   34000   31500      0

## 함수로 만들기

In [51]:
# 조인스부동산 아파트 조회

import pandas as pd
import requests
from bs4 import BeautifulSoup

def get_areacode():
    df_areacode = pd.read_csv('https://goo.gl/tM6r3v', sep='\t', dtype={'법정동코드':str, '법정동명':str})
    df_areacode = df_areacode[df_areacode['폐지여부'] == '존재']
    df_areacode = df_areacode[['법정동코드', '법정동명']]
    return df_areacode

def get_province():
    df_areacode = get_areacode()
    df_province = df_areacode[ df_areacode['법정동코드'].str.contains('\d{2}0{8}|36110{6}')]
    return df_province


def joins_realasset(areacode = ''):
    url = 'http://price.joinsland.joins.com/ajax/price.info.dongapt.asp?mcateGroup=A1&mcateCode=A1A3A4&areaCode=' + areacode

    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'lxml')
    values_list = []

    table = soup.find('table', attrs={'class':'tbl_compare'})
    trs = table.tbody.find_all('tr')
    rowspan_val = ''

    for tr in trs:
        tds = tr.find_all('td')
        if tds[0].has_attr('rowspan'):
            rowspan_val = tds[0].text
            단지명, 면적, 매매가, 매물, 전세가, 전세_매물 = tds[0].text, tds[1].text, tds[2].text, tds[3].text, tds[4].text, tds[5].text
        else:
            단지명, 면적, 매매가, 매물, 전세가, 전세_매물 = rowspan_val, tds[0].text, tds[1].text, tds[2].text, tds[3].text, tds[4].text
        매매가_저 = int(매매가.split(' ~ ')[0].replace(',', ''))
        매매가_고 = int(매매가.split(' ~ ')[1].replace(',', ''))
        전세가_저 = int(전세가.split(' ~ ')[0].replace(',', ''))
        전세가_고 = int(전세가.split(' ~ ')[1].replace(',', ''))
        values_list.append([단지명, 면적, 매매가_저, 매매가_고, 매물, 전세가_저, 전세가_고, 전세_매물])

    cols = ['단지명', '면적', '매매가_저', '매매가_고', '매물', '전세가_저', '전세가_고', '전세가_매물']   
    df = pd.DataFrame(values_list, columns=cols)
    return df

## 검색과 활용

In [52]:
area = '신사동'
area_code = df_areacode[df_areacode['법정동명'].str.contains(area)]
area_code

           법정동코드           법정동명
582   1138010900  서울특별시 은평구 신사동
1043  1168010700  서울특별시 강남구 신사동

In [53]:
area = '강남구 신사동'
area_code = df_areacode[df_areacode['법정동명'].str.contains(area)]['법정동코드'].values[0]
area_code

'1168010700'

In [54]:
joins_realasset(area_code)

              단지명    면적   매매가_저   매매가_고 매물   전세가_저   전세가_고 전세가_매물
0      대원칸타빌(아파트)    85   80000   91500  0   44000   47500      0
1      대원칸타빌(아파트)  107B  117500  127500  0   57500   61000      0
2      대원칸타빌(아파트)   123  122500  137500  0   61000   65500      0
3      대원칸타빌(아파트)   144  150000  165000  0   82500   92500      0
4      로데오현대(아파트)    73   71500   82500  0   37500   41000      0
5      로데오현대(아파트)   114   95000  105000  0   52500   56500      0
6      로데오현대(아파트)  122A  107500  121500  0   56500   61500      0
7         신성(아파트)    72   91500   98000  0   44500   49000      0
8         신성(아파트)    98  114500  127000  0   53000   58500      0
9   압구정하이츠파크(아파트)   234  307500  340000  1  205000  215000      0
10  압구정하이츠파크(아파트)   270  325000  357500  0  212500  230000      0
11      현대맨션(아파트)   147  200000  211000  0   78000   84000      0
12      현대맨션(아파트)   147  200000  211000  0   78000   84000      0
13      현대맨션(아파트)   159  211000  220500  0   84000   92500      0
14      현대맨션(아파트)   162  211000  220500  0   84000   92500      0
15      현대맨션(아파트)   191  208000  218000  0   86500   94500      0
16      현대맨션(아파트)   194  208000  218000  0   86500   94500      0
17      현대맨션(아파트)  195B  208000  218000  0   86500   94500      0
18      현대맨션(아파트)  215A  259000  288500  0  101000  111500      0
19      현대맨션(아파트)  213B  259000  288500  0  101000  111500      0
20      현대맨션(아파트)  215C  259000  288500  0  101000  111500      0
21      현대맨션(아파트)   218  259000  288500  0  101000  111500      0